Support hierarchy change operations #8
protegeproject/webprotege-backend-service pull request #8
Opened 2024-06-05 09:24 UTC by soimugeoWB

first we need to merge https://github.com/protegeproject/webprotege-backend-api/pull/8

2024-06-06 17:45 UTC, matthewhorridge requested changes

2024-06-06 17:45 UTC, matthewhorridge commented on src/main/java/edu/stanford/protege/webprotege/bulkop/EditParentsChangeListGenerator.java
> +                if (superClass instanceof OWLClass) {
Replace `instanceof` checks with `.isNamed()`

2024-06-06 17:45 UTC, matthewhorridge commented on src/main/java/edu/stanford/protege/webprotege/bulkop/EditParentsChangeListGenerator.java
> +            Set<OWLClass> parentsToAdd = new HashSet<>(parents);
Use var keyword (same for all files)

2024-06-06 17:45 UTC, matthewhorridge commented on src/main/java/edu/stanford/protege/webprotege/bulkop/EditParentsChangeListGenerator.java
> +                .filter(axiom -> axiom.getSuperClass() instanceof OWLClass && parentsToRemove.contains(axiom.getSuperClass()))
Replace this with a filter chain.  Replace `instanceof` with `.isNamed()`

2024-06-06 17:45 UTC, matthewhorridge commented on src/main/java/edu/stanford/protege/webprotege/bulkop/EditParentsChangeListGenerator.java
> +    private void addSubClassOfAxiomToChangeList(OWLClass subclass,
Rename to `addAddSubClassOfAxiomToChangeList`

2024-06-06 17:45 UTC, matthewhorridge commented on src/main/java/edu/stanford/protege/webprotege/ProjectActionHandlerBeansConfiguration.java
Can you replace multiple imports with wild card imports?

2024-06-06 17:45 UTC, matthewhorridge commented on src/main/java/edu/stanford/protege/webprotege/hierarchy/ClassHierarchyProviderImpl.java
Can you write a test for the cycle detection?  To make this easier it might be best to extract the cycle detection as a separate class that has a dependency to the hierarchy provide.  Your call.

2024-06-06 17:45 UTC, matthewhorridge commented on src/main/java/edu/stanford/protege/webprotege/hierarchy/HierarchyCycleException.java
> +        super("Changed class hierarchy contains a cycle!");
Remove exclamation mark please

2024-06-06 17:45 UTC, matthewhorridge commented on src/test/java/edu/stanford/protege/webprotege/dispatch/impl/ApplicationActionHandlerRegistry_Test.java
> +@SpringBootTest(classes = WebprotegeBackendMonolithApplication.class)
Do you need to remove the `webprotege.rabbitmq.commands-subscribe=false` here?

2024-06-10 10:56 UTC, soimugeoWB commented
Hello! i think it's done now. Thank you for the review!

2024-06-17 11:23 UTC, alexsilaghi reviewed
waiting for @matthewhorridge  decision with the events in FE

2024-06-17 11:23 UTC, alexsilaghi commented on src/main/resources/application-local.properties
> +logging.level.root=DEBUG
please, dont leave it at debug.

2024-06-17 15:50 UTC, merged